package tw.com.springboot.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_DEPT.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_DEPT.NAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_DEPT.ID
     *
     * @return the value of SPRINGBOOT_DEPT.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_DEPT.ID
     *
     * @param id the value for SPRINGBOOT_DEPT.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_DEPT.NAME
     *
     * @return the value of SPRINGBOOT_DEPT.NAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_DEPT.NAME
     *
     * @param name the value for SPRINGBOOT_DEPT.NAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}