package tw.com.springboot.pojo;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_EMP.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_EMP.LASTNAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_EMP.EMAIL
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_EMP.GENDER
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPRINGBOOT_EMP.DEPT_ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    private String deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_EMP.ID
     *
     * @return the value of SPRINGBOOT_EMP.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_EMP.ID
     *
     * @param id the value for SPRINGBOOT_EMP.ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_EMP.LASTNAME
     *
     * @return the value of SPRINGBOOT_EMP.LASTNAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_EMP.LASTNAME
     *
     * @param lastname the value for SPRINGBOOT_EMP.LASTNAME
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_EMP.EMAIL
     *
     * @return the value of SPRINGBOOT_EMP.EMAIL
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_EMP.EMAIL
     *
     * @param email the value for SPRINGBOOT_EMP.EMAIL
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_EMP.GENDER
     *
     * @return the value of SPRINGBOOT_EMP.GENDER
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_EMP.GENDER
     *
     * @param gender the value for SPRINGBOOT_EMP.GENDER
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPRINGBOOT_EMP.DEPT_ID
     *
     * @return the value of SPRINGBOOT_EMP.DEPT_ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPRINGBOOT_EMP.DEPT_ID
     *
     * @param deptId the value for SPRINGBOOT_EMP.DEPT_ID
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }
}