server:
  port: 8081
spring:
  profiles:
    active: prod
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: prod