package tw.com.springboot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.com.springboot.pojo.Dept;
import tw.com.springboot.pojo.DeptExample;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    Dept selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPRINGBOOT_DEPT
     *
     * @mbggenerated Mon Oct 10 09:02:47 CST 2022
     */
    int updateByPrimaryKey(Dept record);
}